import { NgClass } from "@angular/common";
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  OnDestroy,
  OnInit,
  ViewChild
} from "@angular/core";
import { FormsModule } from "@angular/forms";
import { MatButtonModule } from "@angular/material/button";
import { MatDialog } from "@angular/material/dialog";
import { MatFormFieldModule } from "@angular/material/form-field";
import { MatIconModule } from "@angular/material/icon";
import { MatInputModule } from "@angular/material/input";
import { MatTooltipModule } from "@angular/material/tooltip";
import { debounceTime } from "rxjs";
import { MapColors } from "../../constants/map-colors";
import { RGBAColor } from "../../models/map-color";
import {
  MapColorPalette,
  MapDialogInputData,
  MapDialogOutputData,
  MapOrigin
} from "../../models/map-dialog-data";
import { AnvilService } from "../../services/anvil/anvil-service";
import { FileReaderService } from "../../services/file-reader/file-reader-service";
import {
  LocalStorageKey,
  LocalStorageService
} from "../../services/local-storage/local-storage";
import { CoordInput } from "./coord-input/coord-input";
import { MapDialogComponent } from "./map-dialog/map-dialog";
import { Chunk } from "../../models/chunk";
import { Coords } from "../../models/coords";
import { Dimensions } from "../../models/dimensions";
import { ChunkMapData } from "../../models/chunk-map-data";

@Component({
  selector: "app-map",
  imports: [
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    FormsModule,
    MatTooltipModule,
    CoordInput,
    NgClass
  ],
  templateUrl: "./map.html",
  styleUrl: "./map.scss"
})
export class MapComponent implements OnInit, AfterViewInit, OnDestroy {
  private readonly fileReaderService = inject(FileReaderService);
  private readonly anvilService = inject(AnvilService);
  private readonly localStorageService = inject(LocalStorageService);
  private readonly dialog = inject(MatDialog);

  // A reference to our canvas.
  @ViewChild("map") private canvasRef?: ElementRef<HTMLCanvasElement>;

  private readonly CHUNK_LENGTH = 16;
  private readonly BLOCKS_IN_CHUNK = this.CHUNK_LENGTH * this.CHUNK_LENGTH;
  private readonly MIN_CANVAS_TO_MAP_RATIO = 4;
  private readonly MAX_MAP_LENGTH_CHUNKS = 25;
  private readonly MAX_STORED_CHUNK_IMAGES =
    this.MAX_MAP_LENGTH_CHUNKS * this.MAX_MAP_LENGTH_CHUNKS * 10;

  // An event emitter used to signal and time when the window is resized and thus the canvas should be resized.
  private readonly resizeCanvasEmitter: EventEmitter<void> = new EventEmitter();

  // Region files processed and their data. Keys are strings in the format "x,z".
  private readonly regionFilePromises: Map<string, Promise<ArrayBuffer>> =
    new Map();

  /**
   * Chunk's that have already been drawn. Keys are strings in the format "x,z".
   * If the chunk's data was present, the value contains the created chunk image.
   * Otherwise, the value is null (the chunk has not yet been generated by Minecraft).
   */
  private readonly chunkImagePromises: Map<
    string,
    Promise<ImageBitmap | null>
  > = new Map();

  /**
   * If a chunk's map data is required to create another chunk's image but not its own,
   * we store the chunk's map data in this map. Keys are strings in the format "x,z".
   * That way, if the chunk needs to be drawn in the future, we do not need to
   * fetch the chunk's map data again to generate its image.
   */
  private readonly chunkMapData: Map<string, ChunkMapData | null> = new Map();

  // Keys are strings in the format "x,z".
  private readonly currentlyDrawnChunkKeys: string[] = [];

  protected mapCoords = new Coords();
  protected mapYLevel: number;
  /**
   * Chunk images are 16 x 16 map pixels. Given the current position of the map,
   * the map's edges are likely not resting on a chunk border. Thus, there is a
   * negative offset where the map's chunk images are drawn from. That way, only
   * the portion of the chunk that should be visible are visible on the map.
   */
  private readonly mapStartCoords = new Coords();

  /**
   * These two coords are used to track the previous and current mouse positions
   * during a dragging event. These coords will be set in html/css pixels.
   */
  private readonly dragStartHtmlCoords = new Coords();
  private readonly dragHtmlCoords = new Coords();
  private readonly mapDimensions = new Dimensions();
  private readonly mapClearDimensions = new Dimensions();

  private canvas?: HTMLCanvasElement;
  private ctx?: CanvasRenderingContext2D;
  private htmlToMapRatio = 1;
  private canvasToMapRatio = this.MIN_CANVAS_TO_MAP_RATIO;
  private startingXCoord: number;
  private startingYLevel: number;
  private startingZCoord: number;
  private origin: MapOrigin;
  private colorPalette: MapColorPalette;
  private drawLicense: number = 0;

  protected regionFilesProcessed = false;
  protected isMapDragging: boolean = false;

  constructor() {
    const mapSettings = this.localStorageService.get<MapDialogInputData>(
      LocalStorageKey.MAP_SETTINGS
    );
    this.startingXCoord = mapSettings?.startingXCoord ?? 0;
    this.startingZCoord = mapSettings?.startingZCoord ?? 0;
    this.mapCoords.set(this.startingXCoord, this.startingZCoord);
    this.startingYLevel = mapSettings?.startingYLevel ?? 319;
    this.mapYLevel = this.startingYLevel;
    this.origin = mapSettings?.origin ?? "center";
    this.colorPalette = mapSettings?.colorPalette ?? "original";
  }

  ngOnInit(): void {
    this.openMapDialog();
    this.resizeCanvasEmitter.pipe(debounceTime(250)).subscribe(() => {
      this.resizeCanvas();
    });
  }

  ngAfterViewInit(): void {
    this.canvas = this.canvasRef?.nativeElement;
    this.ctx = this.canvas?.getContext("2d") ?? undefined;
    window.addEventListener("resize", this.windowResizeHandler);
    this.resizeCanvas();
  }

  ngOnDestroy(): void {
    window.removeEventListener("resize", this.windowResizeHandler);
    this.resizeCanvasEmitter.unsubscribe();
  }

  /**
   * A draw license is needed to draw on the canvas. Given the asynchronous nature
   * of fetching and creating chunk images, some images might not be ready to draw
   * until much later. This function sets the current draw license needed to draw
   * on the canvas and effectively clears the queue of chunk images waiting to be drawn.
   */
  private setNewDrawLicense() {
    let newDrawLicense: number;
    do {
      newDrawLicense = Math.trunc(Math.random() * 1000);
    } while (newDrawLicense === this.drawLicense);
    this.drawLicense = newDrawLicense;
  }

  protected mapYLevelChange() {
    this.chunkImagePromises.clear();
    this.chunkMapData.clear();
    this.mapCoordInputChange();
  }

  protected mapCoordInputChange() {
    if (!this.isMapDragging) {
      this.drawMap();
    }
  }

  private windowResizeHandler = () => {
    this.resizeCanvasEmitter.emit();
  };

  private resizeCanvas() {
    if (!this.canvas || !this.ctx) return;

    /**
     * Get the html/css pixel dimensions of the canvas.
     * This is the amount of space/pixels it takes up on a webpage (set via CSS).
     */
    const canvasBoundingRect = this.canvas.getBoundingClientRect();

    // Get the number of physical device pixels per html/css pixel.
    const dpr = window.devicePixelRatio || 1;

    /**
     * An html canvas has a set amount of space/pixels it takes up on a webpage (set via CSS).
     * It also has a separate internal coordinate system (set via JS).
     * For the best image quality, set the canvas' inner dimensions so that each canvas pixel is equivalent to one device pixel.
     */
    this.canvas.width = canvasBoundingRect.width * dpr;
    this.canvas.height = canvasBoundingRect.height * dpr;

    /**
     * The map's dimensions are its width and height in Minecraft blocks.
     * The map is drawn on the canvas.
     * Set the number of canvas pixels per map pixel. A map pixel is not a real pixel.
     * It is merely a way to control the maximum number of Minecraft blocks shown on the map,
     * regardless of the size of the canvas.
     */
    this.canvasToMapRatio = Math.max(
      Math.trunc(
        this.canvas.width / this.MAX_MAP_LENGTH_CHUNKS / this.CHUNK_LENGTH
      ),
      this.MIN_CANVAS_TO_MAP_RATIO
    );

    /**
     * Set the map dimensions (measured in Minecraft blocks).
     * Overflow so that the map takes up the entire canvas.
     */
    this.mapDimensions.width = Math.ceil(
      this.canvas.width / this.canvasToMapRatio
    );
    this.mapDimensions.height = Math.ceil(
      this.canvas.height / this.canvasToMapRatio
    );

    /**
     * Set the number of html/css pixels per map pixel.
     * The user can click and drag on the map to move around. When this happens,
     * we will need to interpret the distance the map was dragged. Mouse events capture mouse positions
     * using html/css pixels. So we need to be able to quickly convert from a distance in html/css pixels
     * to map pixels. This process has already been done above:
     * 1) Multiply by the dpr (Device Pixel Ratio) to get the distance in canvas pixels.
     * 2) Then divide by the canvasToMapRatio to get the distance in map pixels.
     */
    this.htmlToMapRatio = dpr / this.canvasToMapRatio;

    /**
     * For drawing on the canvas, we have two coordinate systems that matter:
     * the canvas' internal dimensions and the map's dimensions. So which should we use to draw a Minecraft block/chunk?
     * Preferably, the map's dimensions because each map pixel is one Minecraft block!
     * We can set the canvas renderer's scale so that when shapes and images are drawn on the canvas,
     * it will scale each pixel to the size of a map pixel. Now when drawing, we can simply draw using
     * the map's coordinate system and dimensions.
     */
    this.ctx.scale(this.canvasToMapRatio, this.canvasToMapRatio);
    this.ctx.imageSmoothingEnabled = false;

    if (!this.isMapDragging) {
      this.drawMap();
    }
  }

  protected openMapDialog() {
    const dialogRef = this.dialog.open<
      MapDialogComponent,
      MapDialogInputData,
      MapDialogOutputData
    >(MapDialogComponent, {
      data: {
        startingXCoord: this.startingXCoord,
        startingZCoord: this.startingZCoord,
        startingYLevel: this.startingYLevel,
        origin: this.origin,
        colorPalette: this.colorPalette
      }
    });

    dialogRef.afterClosed().subscribe((data) => {
      if (!data) return;
      const { files, ...storedSettings } = data;
      this.startingXCoord = storedSettings.startingXCoord;
      this.startingZCoord = storedSettings.startingZCoord;
      this.startingYLevel = storedSettings.startingYLevel;
      this.origin = storedSettings.origin;
      this.colorPalette = storedSettings.colorPalette;
      if (files) {
        this.mapCoords.set(this.startingXCoord, this.startingZCoord);
        this.mapYLevel = this.startingYLevel;
        this.processRegionFiles(files);
      } else {
        this.drawMap();
      }
      this.localStorageService.set(
        LocalStorageKey.MAP_SETTINGS,
        storedSettings
      );
    });
  }

  // Load and store all region files
  private async processRegionFiles(files: FileList) {
    this.regionFilePromises.clear();
    this.chunkImagePromises.clear();
    this.chunkMapData.clear();
    const anvilRegex = new RegExp(/^r\.(?<x>-?[0-9]+)\.(?<z>-?[0-9]+)\.mca$/);
    for (const file of files) {
      const regexResult = anvilRegex.exec(file.name);
      if (!regexResult || !regexResult.groups) continue;
      this.regionFilePromises.set(
        `${regexResult.groups["x"]},${regexResult.groups["z"]}`,
        this.fileReaderService.readAsArrayBuffer(file)
      );
    }

    this.regionFilesProcessed = true;
    this.drawMap();
  }

  /**
   * Guaranteed to clear the map whether it is dragging or not.
   */
  private clearMap() {
    this.ctx?.clearRect(
      this.mapStartCoords.x,
      this.mapStartCoords.z,
      this.mapClearDimensions.width,
      this.mapClearDimensions.height
    );
  }

  /**
   * Draws the chunk's image once the promise is resolved and if the license
   * provided is still active.
   */
  private async drawChunkImage(
    chunkImagePromise: Promise<ImageBitmap | null>,
    x: number,
    z: number,
    drawLicenseUsed: number
  ) {
    const chunkImage = await chunkImagePromise;
    if (chunkImage && drawLicenseUsed === this.drawLicense) {
      this.ctx?.drawImage(chunkImage, x, z);
    }
  }

  /**
   * Given the current map coords and the region files, draws the Minecraft chunks onto the map
   */
  protected drawMap() {
    this.setNewDrawLicense();
    const currentDrawLicense = this.drawLicense;

    // Get current map coords
    const currentMapCoords = new Coords(this.mapCoords.x, this.mapCoords.z);

    // Translate coords if origin is in the center
    if (this.origin === "center") {
      currentMapCoords.subtract(
        Math.ceil(this.mapDimensions.width / 2),
        Math.ceil(this.mapDimensions.height / 2)
      );
    }

    // Get chunk coords of current map coords
    const chunkCoords = this.anvilService.worldBlockCoordsToChunkCoords(
      currentMapCoords.x,
      currentMapCoords.z
    );

    // Get starting map coords to begin drawing the chunks. Range (-this.CHUNK_LENGTH, 0]
    const xRemainder = currentMapCoords.x % this.CHUNK_LENGTH;
    const zRemainder = currentMapCoords.z % this.CHUNK_LENGTH;
    this.mapStartCoords.set(
      -1 * (xRemainder >= 0 ? xRemainder : this.CHUNK_LENGTH + xRemainder),
      -1 * (zRemainder >= 0 ? zRemainder : this.CHUNK_LENGTH + zRemainder)
    );

    // Set the map clear dimensions based on the map start coords
    this.mapClearDimensions.setWithDimensions(this.mapDimensions);
    this.mapClearDimensions.add(
      this.CHUNK_LENGTH - this.mapStartCoords.x,
      this.CHUNK_LENGTH - this.mapStartCoords.z
    );

    this.clearMap();
    this.currentlyDrawnChunkKeys.length = 0;
    for (
      let z = this.mapStartCoords.z, chunkZ = chunkCoords.z;
      z < this.mapDimensions.height;
      z += this.CHUNK_LENGTH, ++chunkZ
    ) {
      for (
        let x = this.mapStartCoords.x, chunkX = chunkCoords.x;
        x < this.mapDimensions.width;
        x += this.CHUNK_LENGTH, ++chunkX
      ) {
        const chunkKey = `${chunkX},${chunkZ}`;
        this.currentlyDrawnChunkKeys.push(chunkKey);

        let chunkImagePromise = this.chunkImagePromises.get(chunkKey);

        if (chunkImagePromise) {
          this.drawChunkImage(chunkImagePromise, x, z, currentDrawLicense);
          continue;
        }

        const newChunkImagePromise = this.getChunkImage(chunkX, chunkZ);
        this.drawChunkImage(newChunkImagePromise, x, z, currentDrawLicense);
        this.chunkImagePromises.set(chunkKey, newChunkImagePromise);
      }
    }
    if (this.chunkImagePromises.size > this.MAX_STORED_CHUNK_IMAGES) {
      this.reduceMapByHalf(this.chunkImagePromises);
    }
  }

  private reduceMapByHalf(map: Map<string, unknown>) {
    const keys = map.keys();
    for (let i = map.size / 2; i < map.size; ++i) {
      const key = keys.next().value;
      if (key) map.delete(key);
    }
  }

  /**
   * Given the coordinates of a chunk in a Minecraft world, returns a
   * promise that resolves with the chunk's data if it exists or null
   * if Minecraft has not yet generated the chunk.
   */
  private async getChunk(
    chunkX: number,
    chunkZ: number
  ): Promise<Chunk | null> {
    // Get region data. If it doesn't exist, return null.
    const regionCoords = this.anvilService.worldChunkCoordsToRegionCoords(
      chunkX,
      chunkZ
    );
    const regionData = this.regionFilePromises.get(
      `${regionCoords.x},${regionCoords.z}`
    );
    if (!regionData) {
      return null;
    }

    // Get chunk data. If it doesn't exist or is not fully generated, return null.
    const regionChunkCoords =
      this.anvilService.worldChunkCoordsToRegionChunkCoords(chunkX, chunkZ);
    const chunk = await this.anvilService.getChunkData(
      await regionData,
      regionChunkCoords.x,
      regionChunkCoords.z
    );
    return chunk?.Status === "minecraft:full" ? chunk : null;
  }

  /**
   * Given the coordinates of a chunk in a Minecraft world, returns a
   * promise that resolves with the chunk's generated image if it exists or null
   * if Minecraft has not yet generated the chunk.
   *
   * Additionally, each chunk's image depends on the y levels of the chunk to the north.
   */
  private async getChunkImage(
    chunkX: number,
    chunkZ: number
  ): Promise<ImageBitmap | null> {
    try {
      const chunkKey = `${chunkX},${chunkZ}`;
      let mapData = this.chunkMapData.get(chunkKey);
      if (mapData === null) {
        return null;
      }
      if (!mapData) {
        const chunk = await this.getChunk(chunkX, chunkZ);
        if (!chunk) {
          this.chunkMapData.set(chunkKey, null);
          return null;
        }
        mapData = this.anvilService.getChunkMapData(chunk, this.mapYLevel);
        this.chunkMapData.set(chunkKey, { ...mapData, colorIds: [] });
      }

      const previousChunkKey = `${chunkX},${chunkZ - 1}`;
      let previousMapData = this.chunkMapData.get(previousChunkKey);
      if (previousMapData === undefined) {
        const previousChunk = await this.getChunk(chunkX, chunkZ - 1);
        if (!previousChunk) {
          previousMapData = null;
          this.chunkMapData.set(previousChunkKey, null);
        } else {
          previousMapData = this.anvilService.getChunkMapData(
            previousChunk,
            this.mapYLevel
          );
          this.chunkMapData.set(previousChunkKey, previousMapData);
        }
      }

      const previousYLevels = previousMapData?.yLevels.slice(
        this.BLOCKS_IN_CHUNK - this.CHUNK_LENGTH
      );
      const imageData = new ImageData(this.CHUNK_LENGTH, this.CHUNK_LENGTH);
      for (let i = 0; i < this.BLOCKS_IN_CHUNK; ++i) {
        let color: RGBAColor;
        if (i < this.CHUNK_LENGTH) {
          if (previousYLevels) {
            color = this.getMapColorIdColor(
              mapData.colorIds[i],
              mapData.yLevels[i],
              previousYLevels[i]
            );
          } else {
            color = MapColors[mapData.colorIds[i]].color.same;
          }
        } else {
          color = this.getMapColorIdColor(
            mapData.colorIds[i],
            mapData.yLevels[i],
            mapData.yLevels[i - this.CHUNK_LENGTH]
          );
        }
        const imageDataIndex = i * 4;
        imageData.data[imageDataIndex] = color.r;
        imageData.data[imageDataIndex + 1] = color.g;
        imageData.data[imageDataIndex + 2] = color.b;
        imageData.data[imageDataIndex + 3] = color.a;
      }
      return await createImageBitmap(imageData);
    } catch (error) {
      console.error(error);
      return null;
    }
  }

  private getMapColorIdColor(
    mapColorId: number,
    yLevel: number,
    previousYLevel: number
  ): RGBAColor {
    if (previousYLevel < yLevel) {
      return MapColors[mapColorId].color.above;
    } else if (previousYLevel > yLevel) {
      return MapColors[mapColorId].color.below;
    } else {
      return MapColors[mapColorId].color.same;
    }
  }

  protected mouseDown = (event: MouseEvent) => {
    if (this.isMapDragging) return;
    this.isMapDragging = true;
    this.setNewDrawLicense();
    this.dragStartHtmlCoords.set(event.x, event.y);
    this.dragHtmlCoords.set(event.x, event.y);
    window.addEventListener("mouseup", this.mouseUp);
    requestAnimationFrame(this.animationFrame);
  };

  protected mouseMove = (event: MouseEvent) => {
    if (!this.isMapDragging) return;
    this.dragHtmlCoords.set(event.x, event.y);
  };

  private mouseUp = () => {
    if (!this.isMapDragging) return;
    this.isMapDragging = false;
    window.removeEventListener("mouseup", this.mouseUp);
  };

  private animationFrame = () => {
    if (!this.canvas || !this.ctx) return;

    // Calculate the shift in html pixels.
    let htmlXShift = this.dragHtmlCoords.x - this.dragStartHtmlCoords.x;
    let htmlZShift = this.dragHtmlCoords.z - this.dragStartHtmlCoords.z;

    /**
     * Update the starting html coords to the current ones for
     * the next iteration.
     */
    this.dragStartHtmlCoords.setWithCoords(this.dragHtmlCoords);

    // Calculate the shift in map pixels.
    let mapXShift = htmlXShift * this.htmlToMapRatio;
    let mapZShift = htmlZShift * this.htmlToMapRatio;

    // Update the map coords
    this.mapCoords.subtract(mapXShift, mapZShift);

    this.clearMap();
    this.ctx.translate(mapXShift, mapZShift);
    for (
      let z = this.mapStartCoords.z, chunkIndex = 0;
      z < this.mapDimensions.height;
      z += this.CHUNK_LENGTH
    ) {
      for (
        let x = this.mapStartCoords.x;
        x < this.mapDimensions.width;
        x += this.CHUNK_LENGTH, ++chunkIndex
      ) {
        let chunkImagePromise = this.chunkImagePromises.get(
          this.currentlyDrawnChunkKeys[chunkIndex]
        );

        if (chunkImagePromise) {
          this.drawChunkImage(chunkImagePromise, x, z, this.drawLicense);
        }
      }
    }

    if (this.isMapDragging) {
      requestAnimationFrame(this.animationFrame);
    } else {
      // Reset translation
      this.ctx.setTransform(
        this.canvasToMapRatio,
        0,
        0,
        this.canvasToMapRatio,
        0,
        0
      );

      // Round map coords to whole numbers
      this.mapCoords.round();

      this.drawMap();
    }
  };
}
